Add GitHub Actions for POSIX and S32K148 platform build
eclipse-openbsw/openbsw pull request #16
Opened 2024-11-08 06:59 UTC by shamitha-shashidhara

This pull request introduces a common build action for both POSIX and S32K platforms. The following changes have been made:

**build.yml**: Created a unified build action that supports both POSIX and S32K platforms. Removed step TEST from the build.yml file as it is no longer needed.

2024-11-15 10:20 UTC, ThoFrank approved these changes

2024-11-15 10:20 UTC, ThoFrank commented on .github/workflows/build.yml
> +          ctest --test-dir cmake-build-unit-tests -j4
Please add a new line at the end

2024-11-20 17:04 UTC, ThoFrank requested changes
Please rebase your commit on top of the current main branch. The toolchain filename changed.

Also please update the commit message. It shouldn't contain the same comment multiple times. And it should probably include the git signoff message (Although I am not sure we need that for internal contributions)

2024-11-20 17:04 UTC, ThoFrank commented on .github/workflows/build.yml
> +        run: cmake -B cmake-build-s32k148 -S executables/referenceApp -DBUILD_TARGET_PLATFORM="S32K148EVB" --toolchain ../../admin/cmake/ArmNoneEabi10.3-2021.10.cmake
toolchain filename changed to ``../../admin/cmake/ArmNoneEabi.cmake``

2024-11-21 05:18 UTC, shamitha-shashidhara commented on .github/workflows/build.yml
> +        run: cmake -B cmake-build-s32k148 -S executables/referenceApp -DBUILD_TARGET_PLATFORM="S32K148EVB" --toolchain ../../admin/cmake/ArmNoneEabi10.3-2021.10.cmake
Fixed.

2024-11-21 05:29 UTC, shamitha-shashidhara commented
Thanks for pointing that out! I've made the changes as suggested.

- Updated the toolchain filename.
- Revised the commit message to remove duplicates.

2024-11-25 11:14 UTC, marcmo approved these changes
LGTM

2024-11-25 11:14 UTC, merged