Add workflow badges
eclipse-openbsw/openbsw pull request #38
Opened 2024-12-19 05:03 UTC by SuhashiniNaik

- Updated code-coverage.yml
- coverage.js written for converting coverage.info to json
- Updated README.md and gh-pages

Output for reference:
![Screenshot 2024-12-18 133919](https://github.com/user-attachments/assets/f64cd66f-a8e4-49a3-9894-a0381e7ab221)

2025-01-12 06:13 UTC, marcmo requested changes

2025-01-12 06:13 UTC, marcmo commented on coverage.js
Please put any additional files into the .github folder, not in the root

2025-01-12 06:13 UTC, marcmo commented on coverage.js
I took a look at the parse stuff, I don't think we should use the `lcov-parse` javascript library unless we really need it. Another dependency and seems we can also get the data we want easier, e.g. like this
`lcov --summary coverage/lcov.info | grep lines | awk '{print $2}'`
isn't that all we need?

2025-01-13 10:55 UTC, SuhashiniNaik commented on coverage.js
Yes the command ` lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' ` we can get the coverage percentage but to convert this into a workflow  badge we will need to use [shields.io](https://shields.io/) a third party app to host our Coverage badge. If that is okay? Can I go ahead with it

Also I used to lcov-parse to javascript to covert the` lcov.info `into a JSON, since the JSON will be used to make badge and it will be dynamic.

2025-01-13 12:42 UTC, marcmo commented on coverage.js
let's try to use shields.io and see how that looks

2025-01-15 09:21 UTC, SuhashiniNaik commented on coverage.js
Yes, I have used shields.io to generate the badge in `code-coverage.yml` and the link has been added to `README.md`

NOTE : The updated code coverage percentage link is generated in the` code-coverage.yml` workflow each time it runs. Therefore, the updated coverage badge link must be manually updated in the README.md file whenever there is a change in the code coverage percentage.

2025-01-21 14:25 UTC, marcmo approved these changes
LGTM

2025-01-21 14:25 UTC, merged